name: binder
channels:
  - cdat/label/nightly
  - conda-forge
  - defaults
dependencies:
  - nodejs
  - wget
  - zarr
  - xarray
  - pytest
  - libcf
  - distarray
  - dask
  - dask-kubernetes
  - distributed
  - kubernetes
  - cdtime
  - cdutil
  - genutil
  - libcdms
  - cdat_info
  - numpy
  - esmpy
  - libdrs_f
  - pyopenssl
  - requests
  - lazy-object-proxy
  - jupyter
  - jupyterlab
  - ipywidgets
  - graphviz
  - bokeh
  - rasterio
  - vcs
  - numba
  - myproxyclient
  - netcdf4
  - scipy
  - julia
  - llvm
  - mesalib
  - nbserverproxy
  - python=3.7
  - tornado=5.1.1
  - pip:
    - dask-labextension
    - cdms2
    - mv2
    - regrid2



