#!/bin/bash
cat << END >  ${CONDA_PREFIX}/etc/conda/activate.d/cdms-activate.sh
#!/bin/bash
export UVCDAT_ANONYMOUS_LOG="NO"
END
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension


find $CONDA_DIR/lib/ -name "libLLVM*" -exec ln -s {} $CONDA_DIR/lib/libLLVM.so \;
ls -l $CONDA_DIR/lib/libLLVM.so
juliacmd=`echo 'ENV["LD_LIBRARY_PATH"]="CONDA_PREFIX/lib"' |sed "s%CONDA_PREFIX%${CONDA_PREFIX}%";`
juliacmd=$juliacmd';ENV["JUPYTER"]="jupyter"; using Pkg; Pkg.add(["IJulia", "MeshArrays"]); Pkg.build("ZMQ");'

echo $juliacmd
# Julia stuff
# https://stackoverflow.com/questions/51272077/install-julia-packages-via-command-line/51273146
# https://github.com/JuliaLang/IJulia.jl
# https://github.com/JuliaLang/IJulia.jl/issues/717
julia -e "$juliacmd"

